- README.md
> References 

- CHANGELOG.md
- README.md
- nafas/functions.py
#24 
- CI badge added to `README.md`
- Some functions docstring modified
- Unnecessary parts removed from `CHANGELOG.md`
> Minor edits

- CHANGELOG.md
- setup.py
#28 
- Sounds bug in pypi fixed
> Sounds bug

- CHANGELOG.md
- nafas/__main__.py
> End of program

- AUTHORS.md
- README.md
- CI badges bug fixed
- TOC removed
- Title updated
- `AUTHORS.md` updated
> `README.md` modification

- CHANGELOG.md
- SECURITY.md
- otherfiles/version_check.py
> SECURITY.md

- otherfiles/RELEASE.md
> Release instructions

- CHANGELOG.md
- NAFAS.spec
- otherfiles/RELEASE.md
- otherfiles/version_check.py
> Build system modification

- .github/workflows/test.yml
- README.md
- autopep8.bat
- autopep8.sh
- dev-requirements.txt
- otherfiles/version_check.py
- setup.cfg
- Test system modified
- `README.md` modified
> Test system modification

- CHANGELOG.md
- nafas/__main__.py
- nafas/params.py
> Exit message

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- NAFAS.spec
- README.md
- SECURITY.md
- nafas/params.py
- otherfiles/Version.rc
- otherfiles/version_check.py
- setup.py
close #49 
close #70 
close #91 
Version 0.7
> Version 0.7

- CHANGELOG.md
- nafas/functions.py
- nafas/params.py
- test/test.py
> Program details

- CHANGELOG.md
- PROGRAMS.md
- README.md
- nafas/params.py
- test/test.py
#122 
- Box program added
References:
1. https://health.clevelandclinic.org/box-breathing-benefits
2. https://www.medicalnewstoday.com/articles/321805#how-to-do-it
> Box Breathing

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- NAFAS.spec
- README.md
- SECURITY.md
- nafas/params.py
- otherfiles/Version.rc
- otherfiles/version_check.py
- setup.py
fix #99 
fix #122 
Version 1.0
> Version 1.0

- CHANGELOG.md
- README.md
> Image Size

- CHANGELOG.md
- README.md
- nafas/__main__.py
- `--skip-intro` argument added
> Skip Intro

- nafas/__main__.py
- nafas/params.py
- test/test.py
#132 
- Survey link changed to https://opsclb.li/nafas/form
> Survey link

- nafas/functions.py
- nafas/params.py
- test/test.py
#132 
Previously, we hadn't had the Nafas version in the survey form link. this PR adds that to the link.
> Nafas Version Added to the Survey Link

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- NAFAS.spec
- README.md
- SECURITY.md
- nafas/params.py
- otherfiles/RELEASE.md
- otherfiles/Version.rc
- otherfiles/version_check.py
- setup.py
- test/test.py
> Version 1.1

- CHANGELOG.md
- nafas/__main__.py
- nafas/functions.py
- otherfiles/version_check.py
- setup.py
#131 
Typing hints added to all modules and doc-strings updated.
> Type Hints Added

- .github/ISSUE_TEMPLATE/bug_report.yml
- CHANGELOG.md
- NAFAS.spec
- README.md
- SECURITY.md
- nafas/params.py
- otherfiles/Version.rc
- otherfiles/version_check.py
- setup.py
- test/test.py
fix #131 
fix #142 
fix #143 
Version 1.2
> Version 1.2

- CHANGELOG.md
- README.md
#144 
This PR updates the readme with information about the speakers.
> Speakers Information Added to The Readme
